<?php
declare(strict_types=1);

function fallback_articles(): array
{
    return [
        [
            'id' => 1,
            'title' => 'Dortmund und Bayern uben sich in Psychospielchen',
            'slug' => 'dortmund-und-bayern-psychospielchen',
            'category' => 'Sport',
            'image' => 'assets/img/article-hero.png',
            'summary' => 'Im Fernduell mit den Munchnern um die Meisterschaft redet sich der BVB stark. Die Bayern antworten mit selbstbewussten Tonen.',
            'content' => 'Dusseldorf. Im Fernduell mit den Munchnern um die Meisterschaft redet sich der BVB stark. Er beansprucht die Position des Teams, das alles zu gewinnen hat. Die Bayern antworten mit selbstbewussten Tonen.\n\nMitte der Woche beschlich Hans-Joachim Watzke ein unerklarliches Gefuhl. Zuletzt habe ihm so etwas vermutlich in der Pubertat ereilt, als er wie alle Jungs zwischen 13 und 16 nicht so recht wusste, wohin mit sich. Aber mittlerweile weiss der 59-Jahrige Geschaftsfuhrer von Borussia Dortmund das ganz genau.\n\nDie Psychospielchen zwischen den beiden seit langem fuhrenden deutschen Klubs wurden schon mal mit groberen Werkzeugen ausgetragen. Heute geht es eher um Worte, Zeichen und kleine Verschiebungen in der Offentlichkeit.\n\nGanz sicher aber dient die Veroffentlichung seiner Befindlichkeit in erster Linie einem Zweck: Sie soll den grossen Gegner kurz vor dem Ziel verunsichern.',
            'author' => 'Robert Peters',
            'created_at' => '2019-05-17',
            'published' => 1,
        ],
        [
            'id' => 2,
            'title' => 'Cacau halt mildes Urteil nach Rassismus-Eklat fur sehr bitter',
            'slug' => 'cacau-urteil-rassismus-eklat',
            'category' => 'Sport',
            'image' => 'assets/img/sport-2.png',
            'summary' => 'Drei Manner haben Nationalspieler beleidigt. Der Integrationsbeauftragte Cacau reagiert enttauscht auf das Urteil.',
            'content' => 'Der fruhere Nationalspieler Cacau hat das milde Urteil nach einem Rassismus-Eklat deutlich kritisiert. Fur ihn bleibt die Entscheidung ein falsches Signal.\n\nSport lebt von Fairness, Respekt und klaren Regeln. Wenn diese Grundsatze verletzt werden, muss eine Gesellschaft sichtbar reagieren.',
            'author' => 'Philipp Oldenburg',
            'created_at' => '2019-05-17',
            'published' => 1,
        ],
        [
            'id' => 3,
            'title' => 'Max Kruse verlasst Werder Bremen',
            'slug' => 'max-kruse-verlasst-werder-bremen',
            'category' => 'Sport',
            'image' => 'assets/img/sport-3.png',
            'summary' => 'Mannschaftskapitan Max Kruse verlasst nach der Saison Werder Bremen. Der Vertrag lauft zum 30. Juni aus.',
            'content' => 'Max Kruse wird Werder Bremen verlassen. Der Klub teilte mit, dass es keine Verlangerung des auslaufenden Vertrags geben wird.\n\nDer Angreifer gehorte zu den pragenden Figuren der Mannschaft und war sportlich wie kommunikativ ein wichtiger Fixpunkt.',
            'author' => 'RP Redaktion',
            'created_at' => '2019-05-17',
            'published' => 1,
        ],
        [
            'id' => 4,
            'title' => 'USA heben Zolle gegen Mexiko und Kanada auf',
            'slug' => 'usa-heben-zolle-auf',
            'category' => 'Politik',
            'image' => 'assets/img/politik-1.png',
            'summary' => 'US-Prasident Donald Trump kundigte die Aufhebung der Zolle an und rief den Kongress zur Billigung eines Handelspakts auf.',
            'content' => 'Die USA heben Zolle gegen Mexiko und Kanada auf. Die Entscheidung soll den Weg fur ein neues Handelsabkommen freimachen.\n\nIn Washington wird die Entscheidung als Signal der Entspannung gelesen, auch wenn wichtige Detailfragen weiter offen bleiben.',
            'author' => 'RP Redaktion',
            'created_at' => '2019-05-17',
            'published' => 1,
        ],
        [
            'id' => 5,
            'title' => 'Zahlreiche EU-Diplomaten sind sauer auf Rumanien',
            'slug' => 'eu-diplomaten-kritisieren-rumanien',
            'category' => 'Politik',
            'image' => 'assets/img/politik-2.png',
            'summary' => 'Rumanien hat derzeit den Vorsitz unter den EU-Staaten inne. Diplomaten kritisieren die Nutzung der Rolle fur eigene Zwecke.',
            'content' => 'In Brussel wachst die Kritik an Rumanien. Mehrere Diplomaten sehen die Ratsprasidentschaft durch innenpolitische Interessen belastet.\n\nDas Treffen der Finanzminister wurde von Spannungen begleitet. Hinter verschlossenen Turen ist von Vertrauensverlust die Rede.',
            'author' => 'RP Redaktion',
            'created_at' => '2019-05-17',
            'published' => 1,
        ],
        [
            'id' => 6,
            'title' => 'Labour erklart Brexit-Gesprache fur gescheitert',
            'slug' => 'labour-brexit-gesprache-gescheitert',
            'category' => 'Politik',
            'image' => 'assets/img/politik-3.png',
            'summary' => 'Wochenlang wurde verhandelt, die Gesprache enden nun in einer Sackgasse. Das Rennen um die Nachfolge ist in vollem Gang.',
            'content' => 'Die britische Labour-Partei hat die Gesprache mit der Regierung uber einen Brexit-Kompromiss fur gescheitert erklart.\n\nDamit steigt der Druck auf Premierministerin Theresa May. Im Parlament bleibt die Lage unubersichtlich.',
            'author' => 'RP Redaktion',
            'created_at' => '2019-05-17',
            'published' => 1,
        ],
    ];
}
